# Generated by Django 3.2.8 on 2021-10-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20211015_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuesModel',
        ),
    ]
