# Generated by Django 3.2.8 on 2021-10-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_questions_quesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quesmodel',
            options={'ordering': ['title'], 'verbose_name': 'Questions', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelTable(
            name='quesmodel',
            table='Questions',
        ),
    ]
