# Generated by Django 3.2.8 on 2021-10-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_questioncontents_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesmodel',
            name='catagory',
            field=models.CharField(choices=[('AA', 'AA'), ('BB', 'BB'), ('test', 'test')], max_length=128, null=True, verbose_name='분류'),
        ),
    ]
