# Generated by Django 3.2.8 on 2021-10-20 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0007_auto_20211016_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('음주운전', '음주운전'), ('공무집행방해', '공무집행방해'), ('도주치사상(뺑소니)', '도주치사상(뺑소니)'), ('사기죄', '사기죄'), ('명예훼손', '명예훼손'), ('모욕죄', '모욕죄'), ('공연음란죄', '공연음란죄'), ('강제추행', '강제추행'), ('강간', '강간'), ('뇌물', '뇌물'), ('보이스피싱', '보이스피싱'), ('카촬', '카촬'), ('주거침입', '주거침입'), ('통매음', '통매음'), ('교통범죄(신호위반 등) (교통특례법)', '교통범죄(신호위반 등) (교통특례법)'), ('폭행, 상해 등 폭력범죄', '폭행, 상해 등 폭력범죄'), ('마약', '마약'), ('도박', '도박'), ('강도', '강도'), ('업무방해', '업무방해'), ('협박', '협박'), ('운전자폭행', '운전자폭행'), ('성매매', '성매매'), ('아청법', '아청법'), ('음주측정거부', '음주측정거부'), ('절도', '절도'), ('성범죄 전반', '성범죄 전반'), ('코로나방역수칙위반(감염병예방법)', '코로나방역수칙위반(감염병예방법)'), ('재물손괴', '재물손괴'), ('아동학대', '아동학대'), ('횡령, 배임', '횡령, 배임')], max_length=128, null=True, verbose_name='분류')),
                ('question', models.CharField(max_length=200, null=True)),
                ('op1', models.CharField(max_length=200, null=True)),
                ('op2', models.CharField(max_length=200, null=True)),
                ('op3', models.CharField(max_length=200, null=True)),
                ('op4', models.CharField(max_length=200, null=True)),
                ('op5', models.CharField(max_length=200, null=True)),
                ('ans', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'db_table': 'Quiz',
                'ordering': ['quiz_title'],
            },
        ),
        migrations.CreateModel(
            name='QuizContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_title', models.CharField(max_length=128, unique=True, verbose_name='quiz_title')),
                ('category', models.CharField(choices=[('음주운전', '음주운전'), ('공무집행방해', '공무집행방해'), ('도주치사상(뺑소니)', '도주치사상(뺑소니)'), ('사기죄', '사기죄'), ('명예훼손', '명예훼손'), ('모욕죄', '모욕죄'), ('공연음란죄', '공연음란죄'), ('강제추행', '강제추행'), ('강간', '강간'), ('뇌물', '뇌물'), ('보이스피싱', '보이스피싱'), ('카촬', '카촬'), ('주거침입', '주거침입'), ('통매음', '통매음'), ('교통범죄(신호위반 등) (교통특례법)', '교통범죄(신호위반 등) (교통특례법)'), ('폭행, 상해 등 폭력범죄', '폭행, 상해 등 폭력범죄'), ('마약', '마약'), ('도박', '도박'), ('강도', '강도'), ('업무방해', '업무방해'), ('협박', '협박'), ('운전자폭행', '운전자폭행'), ('성매매', '성매매'), ('아청법', '아청법'), ('음주측정거부', '음주측정거부'), ('절도', '절도'), ('성범죄 전반', '성범죄 전반'), ('코로나방역수칙위반(감염병예방법)', '코로나방역수칙위반(감염병예방법)'), ('재물손괴', '재물손괴'), ('아동학대', '아동학대'), ('횡령, 배임', '횡령, 배임')], max_length=128, verbose_name='분류')),
                ('cert', models.BooleanField(default=False, verbose_name='수료여부')),
                ('score', models.IntegerField(default=0, null=True, verbose_name='점수')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': 'QuizContents',
                'verbose_name_plural': 'QuizContents',
                'db_table': 'QuizContents',
                'ordering': ['quiz_title'],
            },
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
        migrations.DeleteModel(
            name='QuestionContents',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.quizcontents', verbose_name='quiz_title'),
        ),
    ]
