# Generated by Django 3.2.8 on 2021-10-20 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0008_auto_20211020_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcontents',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='quizcontents',
            name='score',
        ),
        migrations.AlterField(
            model_name='quizcontents',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
