# Generated by Django 3.2.8 on 2021-10-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_remove_quizcontents_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcontents',
            name='quiz_title',
            field=models.CharField(max_length=128, verbose_name='quiz_title'),
        ),
    ]
