# Generated by Django 3.2.8 on 2021-10-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_remove_product_slug'),
        ('exam', '0012_quizcontents_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcontents',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu.product', verbose_name='상품명'),
        ),
    ]
