# Generated by Django 3.2.8 on 2021-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_quizcontents_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcontents',
            name='num_exam',
            field=models.IntegerField(default=3, verbose_name='응시기회'),
        ),
    ]
