# Generated by Django 3.2.8 on 2021-11-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_quizcontents_num_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcontents',
            name='study_cert',
            field=models.BooleanField(default=False, verbose_name='응시조건여부'),
        ),
    ]
