# Generated by Django 3.2.8 on 2021-11-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='주소'),
        ),
    ]
