# Generated by Django 3.2.8 on 2021-10-20 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edu', '0014_remove_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='구매일')),
                ('certificated', models.BooleanField(default=False, verbose_name='수료여부')),
                ('stayedTime', models.CharField(default='', max_length=200, null=True, verbose_name='머문시간')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.product', verbose_name='상품명')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
            options={
                'verbose_name': 'PurchasedItem',
                'verbose_name_plural': 'PurchasedItem',
                'ordering': ('registered_date',),
            },
        ),
    ]
