# Generated by Django 3.2.8 on 2021-10-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='stayedTime',
            field=models.CharField(default='0', max_length=200, null=True, verbose_name='머문시간'),
        ),
    ]
