# Generated by Django 3.2.8 on 2021-10-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_purchaseditem_stayedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseditem',
            name='stayedTime',
            field=models.JSONField(default=[], null=True, verbose_name='머문시간'),
        ),
    ]
