# Generated by Django 3.2.8 on 2021-10-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educontents',
            options={'verbose_name': '교육자료', 'verbose_name_plural': '교육자료'},
        ),
        migrations.AlterModelTable(
            name='educontents',
            table='교육자료',
        ),
    ]
