# Generated by Django 3.2.8 on 2021-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20211015_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educontents',
            name='catagory',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=128, verbose_name='분류'),
        ),
    ]
