# Generated by Django 3.2.8 on 2021-10-15 08:19

from django.db import migrations, models
import edu.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_alter_educontents_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='educontents',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='educontents',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=edu.models.get_file_path, verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='educontents',
            name='catagory',
            field=models.CharField(choices=[('AA', 'AA'), ('BB', 'BB'), ('test', 'test')], max_length=128, verbose_name='분류'),
        ),
    ]
