# Generated by Django 3.2.8 on 2021-10-15 08:23

from django.db import migrations, models
import edu.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20211015_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='educontents',
            name='upload_images',
            field=models.FileField(blank=True, null=True, upload_to=edu.models.get_file_path, verbose_name='이미지파일'),
        ),
    ]
