# Generated by Django 3.2.8 on 2021-10-16 03:12

from django.db import migrations, models
import django.db.models.deletion
import edu.models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_alter_educontents_upload_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('음주운전', '음주운전'), ('공무집행방해', '공무집행방해'), ('도주치사상(뺑소니)', '도주치사상(뺑소니)'), ('사기죄', '사기죄'), ('명예훼손', '명예훼손'), ('모욕죄', '모욕죄'), ('공연음란죄', '공연음란죄'), ('강제추행', '강제추행'), ('강간', '강간'), ('뇌물', '뇌물'), ('보이스피싱', '보이스피싱'), ('카촬', '카촬'), ('주거침입', '주거침입'), ('통매음', '통매음'), ('교통범죄(신호위반 등) (교통특례법)', '교통범죄(신호위반 등) (교통특례법)'), ('폭행, 상해 등 폭력범죄', '폭행, 상해 등 폭력범죄'), ('마약', '마약'), ('도박', '도박'), ('강도', '강도'), ('업무방해', '업무방해'), ('협박', '협박'), ('운전자폭행', '운전자폭행'), ('성매매', '성매매'), ('아청법', '아청법'), ('음주측정거부', '음주측정거부'), ('절도', '절도'), ('성범죄 전반', '성범죄 전반'), ('코로나방역수칙위반(감염병예방법)', '코로나방역수칙위반(감염병예방법)'), ('재물손괴', '재물손괴'), ('아동학대', '아동학대'), ('횡령, 배임', '횡령, 배임')], max_length=128)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category',),
            },
        ),
        migrations.RemoveField(
            model_name='educontents',
            name='catagory',
        ),
        migrations.AddField(
            model_name='educontents',
            name='category',
            field=models.CharField(choices=[('음주운전', '음주운전'), ('공무집행방해', '공무집행방해'), ('도주치사상(뺑소니)', '도주치사상(뺑소니)'), ('사기죄', '사기죄'), ('명예훼손', '명예훼손'), ('모욕죄', '모욕죄'), ('공연음란죄', '공연음란죄'), ('강제추행', '강제추행'), ('강간', '강간'), ('뇌물', '뇌물'), ('보이스피싱', '보이스피싱'), ('카촬', '카촬'), ('주거침입', '주거침입'), ('통매음', '통매음'), ('교통범죄(신호위반 등) (교통특례법)', '교통범죄(신호위반 등) (교통특례법)'), ('폭행, 상해 등 폭력범죄', '폭행, 상해 등 폭력범죄'), ('마약', '마약'), ('도박', '도박'), ('강도', '강도'), ('업무방해', '업무방해'), ('협박', '협박'), ('운전자폭행', '운전자폭행'), ('성매매', '성매매'), ('아청법', '아청법'), ('음주측정거부', '음주측정거부'), ('절도', '절도'), ('성범죄 전반', '성범죄 전반'), ('코로나방역수칙위반(감염병예방법)', '코로나방역수칙위반(감염병예방법)'), ('재물손괴', '재물손괴'), ('아동학대', '아동학대'), ('횡령, 배임', '횡령, 배임')], max_length=128, null=True, verbose_name='분류'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='상품명')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=edu.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.category', verbose_name='분류')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
    ]
