# Generated by Django 3.2.8 on 2021-10-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to='product/', verbose_name='파일'),
        ),
    ]
