# Generated by Django 3.2.8 on 2021-10-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_auto_20211016_1255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=128),
        ),
        migrations.DeleteModel(
            name='EduContents',
        ),
    ]
