# Generated by Django 3.2.8 on 2021-10-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
