# Generated by Django 3.2.8 on 2021-10-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_remove_product_slug'),
        ('cert', '0003_auto_20211016_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='upload_files',
        ),
        migrations.AddField(
            model_name='certification',
            name='address',
            field=models.CharField(default='', max_length=128, verbose_name='주소'),
        ),
        migrations.AddField(
            model_name='certification',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='edu.product', verbose_name='상품명'),
        ),
    ]
