# Generated by Django 3.2.8 on 2021-10-31 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0004_auto_20211031_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='title',
        ),
    ]
