# Generated by Django 3.2.8 on 2021-11-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0005_remove_certification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='user_name',
            field=models.CharField(default='', max_length=128, verbose_name='사용자 이름'),
        ),
    ]
