# Generated by Django 3.2.8 on 2021-11-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0006_certification_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='user_name',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='사용자 이름'),
        ),
    ]
