# Generated by Django 3.2.8 on 2021-11-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0007_alter_certification_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='price',
            field=models.IntegerField(default=30000, verbose_name='수료증 가격'),
        ),
    ]
