# Generated by Django 3.2.8 on 2021-11-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0009_certification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='name',
        ),
    ]
