# Generated by Django 3.2.8 on 2021-11-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0010_remove_certification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='name',
            field=models.CharField(default='', max_length=250, unique=True, verbose_name='수료증명'),
        ),
    ]
