# Generated by Django 3.2.8 on 2021-10-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='이미지'),
        ),
    ]
