# Generated by Django 3.2.8 on 2021-11-03 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_certitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certitem',
            name='image',
        ),
    ]
