# Generated by Django 3.2.8 on 2021-11-03 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0009_certification_name'),
        ('edu', '0014_remove_product_slug'),
        ('cart', '0004_delete_certitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cert.certification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.product')),
            ],
            options={
                'db_table': 'CertItem',
            },
        ),
    ]
