# Generated by Django 3.2.8 on 2021-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_certitem_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item_type',
            field=models.CharField(choices=[('Product', 'Product'), ('Cert', 'Cert')], max_length=8, null=True, verbose_name='아이템 유형'),
        ),
    ]
